name: CI/CD Pipeline for Docker Swarm Deployment

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: 2015lakshmi/phptest:latest
  SERVICE_NAME:  phptest1-stack
  SSH_USER: ec2-user
  SSH_HOST: 43.204.140.69
  SSH_PORT: 22

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Push Docker image
      run: docker push $IMAGE_NAME:latest

    - name: SSH and update Docker Swarm service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ env.SSH_PORT }}
        script: |
          docker pull $IMAGE_NAME:latest
          docker service update --image $IMAGE_NAME:latest $SERVICE_NAME
